package tui

// Generated by tools/tuilayout.mjs from ui/layout.js. Do not edit: change the
// browser panel's layout and run `node tools/tuilayout.mjs`.

Layout_Group :: struct {
	label:  string,
	params: []int,
}

Layout_Section :: struct {
	title:  string,
	groups: []Layout_Group,
}

PANEL_LAYOUT := []Layout_Section {
	{"Master", {
		{"Output", {90}},
		{"Pitch Wheel", {40}},
		{"Controller 1", {86, 87, 50}},
		{"Controller 2", {88, 89, 51}},
	}},
	{"Oscillators", {
		{"Oscillator 1", {0, 76}},
		{"Oscillator 2", {1, 2, 3, 4}},
		{"Both Oscillators", {5, 8, 9, 72, 91}},
		{"Cross Modulation", {45, 6, 7}},
		{"Sub Oscillator", {95, 96, 97}},
	}},
	{"Filter", {
		{"Shape", {14, 19, 20, 23}},
		{"Modulation", {21, 22, 24}},
		{"Envelope", {15, 16, 17, 18}},
	}},
	{"Amplifier", {
		{"Envelope", {25, 26, 27, 28}},
		{"Level", {29, 30}},
	}},
	{"Modulation Envelope", {
		{"Routing", {10, 71, 11}},
		{"Envelope", {12, 13}},
	}},
	{"LFO 1", {
		{"Routing", {57, 42, 41}},
		{"Motion", {43, 44, 67, 68}},
	}},
	{"LFO 2", {
		{"Routing", {58, 47, 46}},
		{"Motion", {48, 49, 69, 70}},
	}},
	{"Delay", {
		{"Routing", {65, 82}},
		{"Time", {35, 83}},
		{"Character", {36, 98, 37}},
	}},
	{"Chorus and Flanger", {
		{"Routing", {66, 64}},
		{"Motion", {52, 53, 54}},
		{"Character", {55, 56}},
	}},
	{"Effect", {
		{"Unit", {77, 78}},
		{"Settings", {79, 80, 81}},
	}},
	{"Equalizer", {
		{"Tone", {60}},
		{"Band", {61, 62, 63}},
	}},
	{"Arpeggiator", {
		{"Pattern", {59, 31, 32}},
		{"Timing", {33, 34}},
	}},
	{"Voice", {
		{"Playing", {38, 94}},
		{"Portamento", {39, 74}},
		{"Unison", {73, 93, 75, 84, 85, 92}},
	}},
}
