// Code generated by "s1probe filtertable --type 1"; do not edit.
//
// The reference Synth1's filter frequency mapping for parameter 14's type 1,
// indexed by parameter 19's resolved state. Method is in docs/null-test.md; in
// short, noise through the filter with the envelope pinned flat, and the
// corner read off the spectrum as the resonant peak's own frequency, resonance held at 107 for the whole sweep.
//
// FILTER_CUTOFF_HZ_24 replaces a chosen exponential from 20 Hz to 20 kHz.
//
// FILTER_ENV_OCTAVES_PER_STEP_24 is how far the corner moves when the envelope
// is at full level, in octaves, per setting of parameter 21. Stored 63 is the
// centre and measures as zero by construction: every entry is relative to the
// corner at that setting.
//
// Both were measured at a base cutoff of 64. The top of each sweep runs past
// what the analysis band can resolve; those entries are extrapolated along the
// curve's own final slope and are marked below.
package engine

// Hertz. Measured from index 5 through 126; outside that, extrapolated.
FILTER_CUTOFF_HZ_24 := [FILTER_TABLE_SIZE]f32{
	19.7210, 20.5805, 21.4773, 22.4133,
	23.3901, 24.4094, 24.6615, 25.5143,
	26.5086, 27.5251, 28.4563, 31.0713,
	33.0391, 34.3371, 35.4620, 37.4763,
	40.3685, 41.9589, 45.1188, 47.0411,
	51.0949, 52.3985, 56.6608, 58.7307,
	64.0315, 66.0904, 71.8357, 73.9408,
	77.8862, 80.0452, 84.5931, 90.4056,
	94.4435, 100.7960, 105.3050, 113.4085,
	118.9997, 128.2888, 133.0612, 142.1595,
	155.0911, 167.4577, 173.8511, 180.4858,
	187.2991, 204.0086, 208.6624, 220.0823,
	226.0966, 248.3777, 264.0732, 277.6207,
	285.6027, 297.4409, 320.1510, 332.1516,
	358.6662, 373.0376, 403.3998, 419.8473,
	454.3705, 470.4250, 511.2742, 525.4434,
	576.0661, 592.4251, 651.8572, 666.5403,
	702.0887, 718.3882, 758.2711, 809.8236,
	848.5129, 904.3960, 947.8817, 1017.1288,
	1059.8415, 1141.7230, 1185.4581, 1285.1012,
	1326.5368, 1447.3106, 1489.3190, 1572.8639,
	1614.2796, 1703.1462, 1812.4097, 1897.0857,
	2031.5753, 2118.8626, 2280.4323, 2371.6709,
	2561.9746, 2661.5706, 2882.4683, 2978.9164,
	3255.4998, 3351.8463, 3533.2572, 3624.0160,
	3803.1984, 4064.9208, 4237.8639, 4565.9186,
	4735.9146, 5147.2421, 5305.9503, 5595.8531,
	5746.5314, 6066.4862, 6459.4960, 6763.0546,
	7247.9289, 7532.3586, 8171.6397, 8426.4994,
	9242.3247, 9514.0961, 9984.5038, 10254.4018,
	10667.4170, 11545.2110, 11915.2840, 12563.7014,
	12956.9909, 13586.1789, 13950.0635, 14445.7584,
}

// How far the filter envelope moves the corner, in octaves per step of
// parameter 21, when the envelope is at full level. Measured by fitting the
// settings that were not pressed against the filter's own floor or ceiling.
//
// Stored as a law rather than a table on purpose. The measured offsets saturate
// at both ends of the sweep, but that is the corner hitting the filter's limits
// at the cutoff it was measured from, not the amount curve bending -- and a
// table would apply one cutoff setting's limits to every other. The engine
// clamps the cutoff it computes, which is where the limits belong.
FILTER_ENV_OCTAVES_PER_STEP_24 :: f32(0.155091)

// The setting at which the envelope contributes nothing. Parameter 21's states
// run from "-63" upwards, so this is the state whose display reads "0".
FILTER_ENV_CENTRE_STATE_24 :: 63

