// Code generated by "s1probe filtertable"; do not edit.
//
// The reference Synth1's filter frequency mapping, indexed by the parameter's
// resolved state. Method is in docs/null-test.md; in short, noise through the
// 12 dB low pass with the filter envelope pinned flat, and the corner read off
// the spectrum as the -3 dB point against a wide-open render.
//
// FILTER_CUTOFF_HZ replaces a chosen exponential from 20 Hz to 20 kHz.
//
// FILTER_ENV_OCTAVES is how far the corner moves when the envelope is at full
// level, in octaves, per setting of parameter 21. It replaces "display/64, times
// an invented six octaves". Stored 63 is the centre and measures as zero by
// construction: every entry is relative to the corner at that setting.
//
// Both were measured at a base cutoff of 64. The top of each sweep runs past
// what the analysis band can resolve; those entries are extrapolated along the
// curve's own final slope and are marked below.
package engine

FILTER_TABLE_SIZE :: 128

// Hertz. Measured through index 116; beyond that, extrapolated.
FILTER_CUTOFF_HZ := [FILTER_TABLE_SIZE]f32{
	23.6057, 23.7141, 23.9718, 24.4371,
	25.0597, 25.8928, 26.9179, 27.9019,
	29.1268, 30.3157, 31.2312, 32.3473,
	33.7595, 35.3260, 37.2564, 39.3567,
	41.7277, 43.8404, 46.0799, 49.3901,
	52.7114, 55.2515, 57.9277, 61.4060,
	65.8156, 69.1250, 72.2477, 76.0593,
	80.2775, 85.0403, 89.8544, 95.6238,
	100.1003, 105.6027, 111.4222, 118.0399,
	125.5718, 135.6757, 142.6719, 151.0441,
	158.7229, 167.9335, 175.5609, 184.1421,
	194.3630, 205.8203, 217.7661, 228.8674,
	241.3567, 255.3928, 271.4208, 285.4279,
	302.3271, 317.4472, 335.9286, 354.8447,
	374.6805, 395.6680, 420.5665, 444.5672,
	471.8243, 498.1298, 527.7583, 555.8044,
	585.2257, 617.9644, 652.0919, 691.5488,
	732.6831, 776.5716, 817.0498, 864.0429,
	909.2573, 970.0036, 1023.5447, 1087.0454,
	1145.2079, 1215.3745, 1278.6286, 1356.5017,
	1425.7747, 1509.9549, 1591.4470, 1685.9202,
	1777.8017, 1880.3742, 1987.2580, 2103.9234,
	2225.7003, 2354.7105, 2492.7881, 2655.5034,
	2809.0095, 2970.2419, 3142.3971, 3316.7904,
	3517.0334, 3727.8162, 3951.1092, 4176.2384,
	4423.8569, 4681.0605, 4959.7017, 5248.1201,
	5562.9838, 5898.9946, 6251.9347, 6626.7347,
	7020.7493, 7497.3856, 7941.8968, 8427.0826,
	8932.3664, 9471.9241, 10011.7327, 10584.8987,
	11166.3461, 11684.5457, 12202.7454, 12720.9450,
	13239.1446, 13757.3442, 14275.5438, 14793.7434,
	15311.9430, 15830.1426, 16348.3422, 16866.5418,
}

// How far the filter envelope moves the corner, in octaves per step of
// parameter 21, when the envelope is at full level. Measured by fitting the
// settings that were not pressed against the filter's own floor or ceiling.
//
// Stored as a law rather than a table on purpose. The measured offsets saturate
// at both ends of the sweep, but that is the corner hitting the filter's limits
// at the cutoff it was measured from, not the amount curve bending -- and a
// table would apply one cutoff setting's limits to every other. The engine
// clamps the cutoff it computes, which is where the limits belong.
FILTER_ENV_OCTAVES_PER_STEP :: f32(0.159530)

// The setting at which the envelope contributes nothing. Parameter 21's states
// run from "-63" upwards, so this is the state whose display reads "0".
FILTER_ENV_CENTRE_STATE :: 63

