// Code generated by "s1probe qtable"; do not edit.
//
// The reference Synth1's resonance curve, as the damping k = 1/Q this engine's
// state variable filter needs to match it, indexed by parameter 20's resolved
// state.
//
// It replaces a straight line, k = 2 - 1.93*r, whose top end was Q = 14. The
// real curve reaches Q = 950 and does almost all of its travel in the last
// fifteen steps of the knob: Q is 2.1 at the centre, 10 at stored 112, 24 at
// 120 and 950 at 127.
//
// Why the old number was so far out is worth keeping. It came from reading the
// resonance off a 1/6-octave band profile, and a 1/6-octave band has a Q of its
// own -- 1/(2^(1/12) - 2^(-1/12)) = 8.651. Any resonance sharper than that is
// smeared into a band-wide peak and reads back as about 8.65 whatever it is.
// The reference measured 8.57 that way, which is the instrument's ceiling to
// within one percent, and it was recorded as the reference's Q.
//
// Method is in docs/null-test.md and in tools/s1probe/resonanceprobe.odin. In
// short: noise through the filter at cutoff 48, and the ratio of the power in
// the band holding the resonance to the power in a band a fixed distance above
// it, which tracks Q without the peak ever having to be resolved. The ratio is
// inverted through the same measurement taken against dsp.Filter itself at known
// damping values, so what is stored is the damping our topology needs, not a Q
// read off one filter design and applied to another.
//
// Both tables are the damping of the *whole filter*, not of one section.
// dsp.filter_set_damping takes the square root for the 24 dB path, where two
// sections in series would otherwise multiply their resonances together.
package engine

FILTER_RESONANCE_TABLE_SIZE :: 128

// The 12 dB responses, measured through the band pass -- the only type whose
// peak is unambiguous at every setting of the knob.
//
// Stored 127 sits at dsp.MIN_DAMPING, which is where f32 stops being able to
// represent the damping at all; see the constant. The reference is at or past
// self-oscillation there, so that entry is a floor rather than a reading.
FILTER_DAMPING := [FILTER_RESONANCE_TABLE_SIZE]f32{
	0.934898, 0.927485, 0.920069, 0.912651,
	0.905230, 0.897810, 0.890402, 0.882992,
	0.875581, 0.868169, 0.860755, 0.853340,
	0.845925, 0.838509, 0.831092, 0.823675,
	0.816257, 0.808839, 0.801422, 0.794005,
	0.786589, 0.779174, 0.771760, 0.764345,
	0.756920, 0.749496, 0.742075, 0.734656,
	0.727239, 0.719826, 0.712416, 0.705001,
	0.697565, 0.690134, 0.682707, 0.675284,
	0.667867, 0.660455, 0.653049, 0.645607,
	0.638169, 0.630738, 0.623313, 0.615897,
	0.608487, 0.601076, 0.593623, 0.586180,
	0.578746, 0.571322, 0.563909, 0.556507,
	0.549047, 0.541595, 0.534156, 0.526730,
	0.519317, 0.511903, 0.504432, 0.496977,
	0.489538, 0.482116, 0.474712, 0.467237,
	0.459770, 0.452323, 0.444897, 0.437491,
	0.429996, 0.422522, 0.415073, 0.407648,
	0.400191, 0.392697, 0.385232, 0.377796,
	0.370348, 0.362840, 0.355365, 0.347924,
	0.340449, 0.332935, 0.325460, 0.318023,
	0.310488, 0.302987, 0.295529, 0.288012,
	0.280494, 0.273026, 0.265497, 0.257969,
	0.250497, 0.242937, 0.235422, 0.227909,
	0.220354, 0.212865, 0.205284, 0.197776,
	0.190211, 0.182699, 0.175133, 0.167626,
	0.160056, 0.152536, 0.145004, 0.137473,
	0.129971, 0.122473, 0.114971, 0.107498,
	0.100042, 0.092604, 0.085192, 0.077801,
	0.070432, 0.063076, 0.055734, 0.048399,
	0.041061, 0.033715, 0.026368, 0.019099,
	0.012148, 0.006078, 0.002569, 0.001050,
}

// The 24 dB low pass, measured through itself.
//
// It is roughly twice the 12 dB damping at the same knob position, and that is
// not a redundancy: a cascade of two two-pole resonances has a different shape
// from one four-pole resonance, so the damping that makes our pair behave like
// the reference's 24 dB filter is not the damping that makes one section behave
// like its 12 dB one.
//
// The first entries are bounds rather than readings. A low pass with the
// resonance off has its maximum at DC and not at the corner, so there is no peak
// to measure, and the inversion comes back against the flat end of the
// calibration.
FILTER_DAMPING_24 := [FILTER_RESONANCE_TABLE_SIZE]f32{
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 1.966486, 1.923815,
	1.881589, 1.840037, 1.800155, 1.760676,
	1.721602, 1.683668, 1.646702, 1.610108,
	1.573885, 1.539174, 1.504825, 1.470821,
	1.437639, 1.405365, 1.373411, 1.341780,
	1.311367, 1.281290, 1.251517, 1.222491,
	1.194153, 1.166103, 1.138457, 1.111740,
	1.085300, 1.059144, 1.033816, 1.008879,
	0.984217, 0.960166, 0.936647, 0.913400,
	0.890619, 0.868448, 0.846551, 0.825033,
	0.804160, 0.783563, 0.763301, 0.743684,
	0.724350, 0.705335, 0.686938, 0.668832,
	0.651049, 0.633849, 0.616947, 0.600382,
	0.584359, 0.568640, 0.553271, 0.538397,
	0.523828, 0.509619, 0.495861, 0.482402,
	0.469298, 0.456590, 0.444166, 0.432085,
	0.420351, 0.408877, 0.397722, 0.386862,
	0.376231, 0.365880, 0.355767, 0.345848,
	0.336178, 0.326694, 0.317370, 0.308264,
	0.299296, 0.290477, 0.281819, 0.273276,
	0.264870, 0.256574, 0.248371, 0.240270,
	0.232211, 0.224181, 0.216111, 0.207942,
	0.199575, 0.190895, 0.181763, 0.172051,
	0.161638, 0.150468, 0.138545, 0.125921,
	0.112643, 0.098662, 0.083810, 0.067795,
	0.049849, 0.031285, 0.017306, 0.003302,
}

// The output gain that goes with the damping above, as a plain amplitude.
//
// Resonance is energy. Our filter passes it and the reference does not, so once
// the real damping curve landed we were up to eleven decibels loud at the top of
// the knob with the timbre already correct -- the spectral metric normalises
// gain away and never saw it.
//
// One table for every response and both slopes, which is a measurement and not a
// convenience: the low pass, the high pass, the band pass and the 24 dB low pass
// all need the same correction to within about a decibel across the whole knob.
// It is independent of the cutoff too, checked at three settings four octaves
// apart, which is what a normalisation of the filter's own noise gain has to be.
//
// State zero is the neutral multiplier. The absolute amp-gain table already
// includes the reference's open-filter output level, so this curve is normalised
// by its measured state-zero value and owns only resonance-dependent level.
// It replaces a k^0.25 on the band-pass output alone, fitted with a saw -- an
// instrument that under-reads a narrowing resonance because its partials fall
// out of the peak as it sharpens.
FILTER_OUTPUT_GAIN := [FILTER_RESONANCE_TABLE_SIZE]f32{
	1.000000, 0.994570, 0.989136, 0.983702,
	0.978263, 0.972829, 0.967398, 0.961969,
	0.956538, 0.951108, 0.945675, 0.940244,
	0.934809, 0.929377, 0.923942, 0.918509,
	0.913075, 0.907641, 0.902207, 0.896774,
	0.891340, 0.885911, 0.880476, 0.875047,
	0.869608, 0.864169, 0.858730, 0.853295,
	0.847861, 0.842431, 0.837001, 0.831565,
	0.826122, 0.820677, 0.815237, 0.809798,
	0.804361, 0.798928, 0.793495, 0.788046,
	0.782597, 0.777148, 0.771707, 0.766273,
	0.760838, 0.755403, 0.749942, 0.744483,
	0.739034, 0.733587, 0.728151, 0.722717,
	0.717247, 0.711783, 0.706325, 0.700877,
	0.695436, 0.689992, 0.684511, 0.679040,
	0.673576, 0.668123, 0.662683, 0.657199,
	0.651714, 0.646242, 0.640787, 0.635345,
	0.629835, 0.624344, 0.618870, 0.613409,
	0.607923, 0.602414, 0.596926, 0.591458,
	0.585981, 0.580458, 0.574959, 0.569485,
	0.563987, 0.558456, 0.552961, 0.547492,
	0.541948, 0.536434, 0.530948, 0.525420,
	0.519895, 0.514409, 0.508873, 0.503347,
	0.497860, 0.492309, 0.486794, 0.481279,
	0.475730, 0.470246, 0.464673, 0.459176,
	0.453608, 0.448109, 0.442532, 0.437023,
	0.431426, 0.425874, 0.420290, 0.414684,
	0.409084, 0.403448, 0.397761, 0.392051,
	0.386299, 0.380477, 0.374601, 0.368629,
	0.362579, 0.356369, 0.349999, 0.343410,
	0.336505, 0.329277, 0.321544, 0.313359,
	0.304423, 0.291687, 0.291261, 0.363214,
}

// The 24 dB path needs its own, which the single table above assumed it did not.
//
// That assumption is recorded above as a measurement -- "the low pass, the high
// pass, the band pass and the 24 dB low pass all need the same correction to
// within about a decibel" -- and it does not survive being checked with the
// filter type the bank actually uses. Driven with noise at three cutoffs four
// octaves apart, the 12 dB responses come back within 0.5 dB across the knob and
// the 24 dB one does not:
//
//   resonance      0     16     32     48     64     80     96    112
//   12 dB      +0.19  +0.20  +0.22  +0.23  +0.23  +0.24  +0.45  +0.53 dB
//   24 dB      -0.99  +1.37  +1.67  +2.07  +2.24  +2.40  +1.94  -0.02
//
// The shapes of the two curves differ as well as their size: ours *gains* level
// as the resonance comes up where the reference *loses* it, which is what a
// four-pole design does and what two cascaded two-pole sections do not. That is
// the same mismatch the damping table already carries its own 24 dB column for.
//
// What is left after this correction is a dependence on cutoff that a curve of
// the resonance knob cannot hold: the error at a given resonance spans about
// 2.5 dB between cutoff 32 and 96, and the entries below are the mean of the
// three. Above stored 112 the reference is at or past self-oscillation and the
// reading is not a level, so the correction is held at unity there.
//
// State zero stays the neutral multiplier here as it does above, and the reason
// is the same cutoff dependence. Driven with noise at cutoff 63 our 24 dB path
// reads 0.99 dB quiet at zero resonance, and correcting that as a gain was tried:
// it is not a gain but a shape, two cascaded two-pole sections having a lower
// -3 dB point than one four-pole design, so it is absent when the signal sits
// well inside the passband. Written in, it made the whole effect unit a decibel
// loud -- the ring modulator, which is a linear crossfade and passes level
// through untouched, went from -0.00 to +0.98 dB -- and that is what a level
// offset applied where there is none looks like.
FILTER_OUTPUT_GAIN_24 := [FILTER_RESONANCE_TABLE_SIZE]f32{
	1.000000, 0.973004, 0.946704, 0.921088,
	0.896133, 0.871831, 0.848165, 0.825117,
	0.802668, 0.788597, 0.774745, 0.761112,
	0.747693, 0.734486, 0.721486, 0.708693,
	0.696103, 0.692557, 0.689006, 0.685449,
	0.681883, 0.678316, 0.674737, 0.671156,
	0.667560, 0.659925, 0.652352, 0.644842,
	0.637394, 0.630010, 0.622684, 0.615414,
	0.608197, 0.602192, 0.596223, 0.590288,
	0.584388, 0.578522, 0.572690, 0.566877,
	0.561098, 0.555856, 0.550641, 0.545454,
	0.540289, 0.535144, 0.530002, 0.524884,
	0.519794, 0.515122, 0.510472, 0.505836,
	0.501189, 0.496561, 0.491951, 0.487360,
	0.482789, 0.478596, 0.474385, 0.470187,
	0.466001, 0.461829, 0.457674, 0.453495,
	0.449322, 0.444780, 0.440265, 0.435773,
	0.431248, 0.426750, 0.422279, 0.417830,
	0.413380, 0.409398, 0.405434, 0.401489,
	0.397543, 0.393569, 0.389616, 0.385684,
	0.381742, 0.378615, 0.375501, 0.372394,
	0.369225, 0.366065, 0.362913, 0.359721,
	0.356519, 0.354521, 0.352460, 0.350376,
	0.348290, 0.346129, 0.343963, 0.341767,
	0.339516, 0.338919, 0.338212, 0.337514,
	0.336716, 0.335922, 0.335019, 0.334119,
	0.333099, 0.334925, 0.336679, 0.338364,
	0.340000, 0.341550, 0.342996, 0.344358,
	0.344818, 0.339622, 0.334377, 0.329046,
	0.323645, 0.318102, 0.312416, 0.306535,
	0.300371, 0.293919, 0.287017, 0.279711,
	0.271734, 0.260366, 0.259986, 0.324212,
}
