// Code generated by "s1probe qtable"; do not edit.
//
// The reference Synth1's resonance curve, as the damping k = 1/Q this engine's
// state variable filter needs to match it, indexed by parameter 20's resolved
// state.
//
// It replaces a straight line, k = 2 - 1.93*r, whose top end was Q = 14. The
// real curve reaches Q = 950 and does almost all of its travel in the last
// fifteen steps of the knob: Q is 2.1 at the centre, 10 at stored 112, 24 at
// 120 and 950 at 127.
//
// Why the old number was so far out is worth keeping. It came from reading the
// resonance off a 1/6-octave band profile, and a 1/6-octave band has a Q of its
// own -- 1/(2^(1/12) - 2^(-1/12)) = 8.651. Any resonance sharper than that is
// smeared into a band-wide peak and reads back as about 8.65 whatever it is.
// The reference measured 8.57 that way, which is the instrument's ceiling to
// within one percent, and it was recorded as the reference's Q.
//
// Method is in docs/null-test.md and in tools/s1probe/resonanceprobe.odin. In
// short: noise through the filter at cutoff 48, and the ratio of the power in
// the band holding the resonance to the power in a band a fixed distance above
// it, which tracks Q without the peak ever having to be resolved. The ratio is
// inverted through the same measurement taken against dsp.Filter itself at known
// damping values, so what is stored is the damping our topology needs, not a Q
// read off one filter design and applied to another.
//
// Both tables are the damping of the *whole filter*, not of one section.
// dsp.filter_set_damping takes the square root for the 24 dB path, where two
// sections in series would otherwise multiply their resonances together.
package engine

FILTER_RESONANCE_TABLE_SIZE :: 128

// The 12 dB responses, measured through the band pass -- the only type whose
// peak is unambiguous at every setting of the knob.
//
// Stored 127 sits at dsp.MIN_DAMPING, which is where f32 stops being able to
// represent the damping at all; see the constant. The reference is at or past
// self-oscillation there, so that entry is a floor rather than a reading.
FILTER_DAMPING := [FILTER_RESONANCE_TABLE_SIZE]f32{
	0.934898, 0.927485, 0.920069, 0.912651,
	0.905230, 0.897810, 0.890402, 0.882992,
	0.875581, 0.868169, 0.860755, 0.853340,
	0.845925, 0.838509, 0.831092, 0.823675,
	0.816257, 0.808839, 0.801422, 0.794005,
	0.786589, 0.779174, 0.771760, 0.764345,
	0.756920, 0.749496, 0.742075, 0.734656,
	0.727239, 0.719826, 0.712416, 0.705001,
	0.697565, 0.690134, 0.682707, 0.675284,
	0.667867, 0.660455, 0.653049, 0.645607,
	0.638169, 0.630738, 0.623313, 0.615897,
	0.608487, 0.601076, 0.593623, 0.586180,
	0.578746, 0.571322, 0.563909, 0.556507,
	0.549047, 0.541595, 0.534156, 0.526730,
	0.519317, 0.511903, 0.504432, 0.496977,
	0.489538, 0.482116, 0.474712, 0.467237,
	0.459770, 0.452323, 0.444897, 0.437491,
	0.429996, 0.422522, 0.415073, 0.407648,
	0.400191, 0.392697, 0.385232, 0.377796,
	0.370348, 0.362840, 0.355365, 0.347924,
	0.340449, 0.332935, 0.325460, 0.318023,
	0.310488, 0.302987, 0.295529, 0.288012,
	0.280494, 0.273026, 0.265497, 0.257969,
	0.250497, 0.242937, 0.235422, 0.227909,
	0.220354, 0.212865, 0.205284, 0.197776,
	0.190211, 0.182699, 0.175133, 0.167626,
	0.160056, 0.152536, 0.145004, 0.137473,
	0.129971, 0.122473, 0.114971, 0.107498,
	0.100042, 0.092604, 0.085192, 0.077801,
	0.070432, 0.063076, 0.055734, 0.048399,
	0.041061, 0.033715, 0.026368, 0.019099,
	0.012148, 0.006078, 0.002569, 0.001050,
}

// The 24 dB low pass, measured through itself.
//
// It is roughly twice the 12 dB damping at the same knob position, and that is
// not a redundancy: a cascade of two two-pole resonances has a different shape
// from one four-pole resonance, so the damping that makes our pair behave like
// the reference's 24 dB filter is not the damping that makes one section behave
// like its 12 dB one.
//
// The first entries are bounds rather than readings. A low pass with the
// resonance off has its maximum at DC and not at the corner, so there is no peak
// to measure, and the inversion comes back against the flat end of the
// calibration.
FILTER_DAMPING_24 := [FILTER_RESONANCE_TABLE_SIZE]f32{
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 2.000000, 2.000000,
	2.000000, 2.000000, 1.966486, 1.923815,
	1.881589, 1.840037, 1.800155, 1.760676,
	1.721602, 1.683668, 1.646702, 1.610108,
	1.573885, 1.539174, 1.504825, 1.470821,
	1.437639, 1.405365, 1.373411, 1.341780,
	1.311367, 1.281290, 1.251517, 1.222491,
	1.194153, 1.166103, 1.138457, 1.111740,
	1.085300, 1.059144, 1.033816, 1.008879,
	0.984217, 0.960166, 0.936647, 0.913400,
	0.890619, 0.868448, 0.846551, 0.825033,
	0.804160, 0.783563, 0.763301, 0.743684,
	0.724350, 0.705335, 0.686938, 0.668832,
	0.651049, 0.633849, 0.616947, 0.600382,
	0.584359, 0.568640, 0.553271, 0.538397,
	0.523828, 0.509619, 0.495861, 0.482402,
	0.469298, 0.456590, 0.444166, 0.432085,
	0.420351, 0.408877, 0.397722, 0.386862,
	0.376231, 0.365880, 0.355767, 0.345848,
	0.336178, 0.326694, 0.317370, 0.308264,
	0.299296, 0.290477, 0.281819, 0.273276,
	0.264870, 0.256574, 0.248371, 0.240270,
	0.232211, 0.224181, 0.216111, 0.207942,
	0.199575, 0.190895, 0.181763, 0.172051,
	0.161638, 0.150468, 0.138545, 0.125921,
	0.112643, 0.098662, 0.083810, 0.067795,
	0.049849, 0.031285, 0.017306, 0.003302,
}

// The output gain that goes with the damping above, as a plain amplitude.
//
// Resonance is energy. Our filter passes it and the reference does not, so once
// the real damping curve landed we were up to eleven decibels loud at the top of
// the knob with the timbre already correct -- the spectral metric normalises
// gain away and never saw it.
//
// One table for every response and both slopes, which is a measurement and not a
// convenience: the low pass, the high pass, the band pass and the 24 dB low pass
// all need the same correction to within about a decibel across the whole knob.
// It is independent of the cutoff too, checked at three settings four octaves
// apart, which is what a normalisation of the filter's own noise gain has to be.
//
// It replaces a k^0.25 on the band-pass output alone, fitted with a saw -- an
// instrument that under-reads a narrowing resonance because its partials fall
// out of the peak as it sharpens.
FILTER_OUTPUT_GAIN := [FILTER_RESONANCE_TABLE_SIZE]f32{
	0.982168, 0.976835, 0.971497, 0.966160,
	0.960819, 0.955482, 0.950148, 0.944815,
	0.939481, 0.934148, 0.928812, 0.923478,
	0.918140, 0.912804, 0.907466, 0.902130,
	0.896794, 0.891456, 0.886119, 0.880783,
	0.875445, 0.870113, 0.864776, 0.859443,
	0.854101, 0.848759, 0.843417, 0.838079,
	0.832742, 0.827408, 0.822075, 0.816737,
	0.811390, 0.806042, 0.800700, 0.795357,
	0.790018, 0.784682, 0.779346, 0.773993,
	0.768641, 0.763290, 0.757946, 0.752609,
	0.747271, 0.741933, 0.736569, 0.731207,
	0.725855, 0.720506, 0.715166, 0.709830,
	0.704457, 0.699091, 0.693730, 0.688379,
	0.683035, 0.677688, 0.672304, 0.666931,
	0.661565, 0.656209, 0.650866, 0.645480,
	0.640093, 0.634719, 0.629360, 0.624015,
	0.618604, 0.613211, 0.607834, 0.602471,
	0.597082, 0.591672, 0.586282, 0.580911,
	0.575531, 0.570107, 0.564707, 0.559330,
	0.553930, 0.548498, 0.543100, 0.537729,
	0.532284, 0.526868, 0.521481, 0.516051,
	0.510624, 0.505236, 0.499799, 0.494371,
	0.488982, 0.483530, 0.478113, 0.472697,
	0.467246, 0.461860, 0.456387, 0.450988,
	0.445520, 0.440118, 0.434641, 0.429230,
	0.423733, 0.418280, 0.412796, 0.407289,
	0.401790, 0.396253, 0.390668, 0.385060,
	0.379410, 0.373693, 0.367921, 0.362056,
	0.356114, 0.350014, 0.343758, 0.337286,
	0.330504, 0.323405, 0.315810, 0.307771,
	0.298995, 0.286486, 0.286067, 0.356738,
}
