// The reference Synth1's 24 dB low-pass corner at resonance 0, indexed by
// parameter 19's resolved state.
//
// Generated by:
//
//   s1probe filtertable <dll> build/filter_table_24_res0.odin --type 1
//
// `FILTER_CUTOFF_HZ_24` is the complementary high-resonance surface, measured
// from the peak at resonance 107. Binding interpolates geometrically between
// the two with the independently measured resonance transition. Keeping this
// table separate makes it impossible to accidentally substitute the resonance-0
// corner globally again; that earlier experiment regressed every high-Q patch.
package engine

// Hertz. Measured through index 120; beyond that, extrapolated by the generator.
FILTER_CUTOFF_HZ_24_LOW_RESONANCE := [FILTER_TABLE_SIZE]f32{
	23.1280, 23.2185, 23.3196, 23.4327,
	23.5592, 23.7009, 23.9494, 24.3400,
	24.7800, 25.2772, 25.8402, 26.4800,
	27.0397, 27.5808, 28.1797, 28.8443,
	29.5846, 30.2036, 30.6948, 31.3161,
	31.9406, 32.6453, 33.4443, 34.3173,
	35.2904, 36.3903, 37.6387, 39.1327,
	40.8539, 42.6788, 44.1449, 45.8071,
	47.7317, 50.3772, 53.4410, 55.4242,
	57.6747, 60.7315, 64.3740, 68.0069,
	70.6928, 73.7593, 77.3258, 81.4749,
	86.0648, 90.8583, 96.0668, 100.6801,
	106.0327, 111.4781, 117.6328, 125.1131,
	134.0498, 141.0214, 148.9043, 157.8673,
	166.7666, 174.9573, 183.4845, 193.3650,
	204.8871, 216.9765, 228.0733, 240.8804,
	255.1097, 271.0736, 285.5707, 302.3700,
	318.5096, 337.2933, 354.8469, 374.7877,
	397.0620, 426.2608, 451.3332, 480.3181,
	508.1855, 540.1980, 568.9186, 602.4664,
	637.2054, 677.7874, 720.2112, 767.8551,
	811.0738, 860.6842, 910.7265, 968.4036,
	1029.1398, 1096.4381, 1165.1749, 1248.4279,
	1328.1986, 1410.7478, 1502.7604, 1598.3270,
	1708.9985, 1816.2351, 1941.0104, 2072.1238,
	2216.9703, 2374.8704, 2539.8552, 2728.4502,
	2919.2840, 3132.0890, 3362.9379, 3620.1269,
	3910.9489, 4255.8665, 4586.0153, 4961.7767,
	5378.0483, 5825.4723, 6331.1436, 6902.4072,
	7514.6899, 8197.1731, 8975.8212, 9855.2600,
	10835.9917, 11518.2347, 12200.4776, 12882.7205,
	13564.9635, 14247.2064, 14929.4493, 15611.6923,
}

// Same fit as the generated resonance-0 table. Its 0.1630 octaves per state
// independently reproduced the envelope-amount law while the base corner moved
// by more than an octave, which is why both surfaces share one blend position.
FILTER_ENV_OCTAVES_PER_STEP_24_LOW_RESONANCE :: f32(0.163046)
