// Code generated by "s1probe lforatetable"; do not edit.
//
// The reference Synth1's free-running LFO speed, in hertz, indexed by the
// parameter's resolved state. Method is in docs/null-test.md: the LFO is pointed
// at the stereo position, which gives a bipolar scalar per frame that nothing
// else in the voice can contaminate, and the crossings of its own mean are
// counted. The render grows until enough cycles fit, so the slow end is measured
// rather than extrapolated.
//
// This replaces a chosen exponential from 0.05 Hz to 40 Hz. Settings that could
// not be resolved -- the LFO moving too little to count, at the very bottom --
// are interpolated geometrically between their neighbours.
package engine

LFO_RATE_TABLE_SIZE :: 128

LFO_RATE_HZ := [LFO_RATE_TABLE_SIZE]f32{
	0.07802, 0.08669, 0.08669, 0.09536,
	0.10403, 0.12120, 0.12120, 0.12120,
	0.12120, 0.12120, 0.13852, 0.13852,
	0.15583, 0.17315, 0.17315, 0.19046,
	0.20778, 0.24176, 0.24176, 0.24176,
	0.24176, 0.24176, 0.27630, 0.27630,
	0.31084, 0.34538, 0.34538, 0.37991,
	0.41445, 0.48097, 0.48097, 0.48097,
	0.48097, 0.48097, 0.54968, 0.61839,
	0.61839, 0.68710, 0.68710, 0.75581,
	0.82452, 0.95186, 0.95186, 1.08784,
	0.95186, 0.95186, 1.08784, 1.22382,
	1.22382, 1.35980, 1.35980, 1.49578,
	1.63177, 1.76775, 1.76775, 1.90373,
	2.03971, 2.17569, 2.31167, 2.44765,
	2.58363, 2.85559, 2.99157, 3.12755,
	3.39951, 3.39951, 3.67147, 3.80745,
	4.07941, 4.35137, 4.62333, 4.89530,
	5.30324, 5.57520, 5.98314, 6.11912,
	6.52706, 6.93500, 7.34294, 7.88686,
	8.43079, 8.70275, 9.24667, 9.92657,
	10.47049, 11.15039, 11.69432, 12.51020,
	13.19010, 13.87000, 14.82187, 15.77373,
	16.58961, 17.54147, 18.62932, 19.71716,
	20.94098, 22.16481, 23.52461, 24.88442,
	26.38020, 27.87599, 29.64373, 31.27550,
	33.31520, 35.21893, 37.25863, 39.57030,
	41.88197, 44.32962, 46.91324, 49.63285,
	52.62442, 55.88795, 59.15148, 62.68697,
	66.35844, 70.43786, 74.38129, 78.86864,
	83.49198, 88.52325, 93.69051, 99.40169,
	105.24884, 111.50394, 118.16698, 124.96600,
}
