// uiparams - emit the parameter table the HTML interface reads.
//
//   odin run tools/uiparams -out:build/uiparams.exe
//
// The interface needs three things per parameter that only this repository knows:
// how many positions the control has, which stored integer each position writes,
// and what the value at that position actually *is* in a real unit.
//
// The third is the point. Synth1's own display is a bare 0..127 for most of the
// interesting controls -- the filter cutoff, every envelope segment, the LFO
// speed, the resonance -- so a interface that echoed the plugin would show a
// number that means nothing. This project has measured what those numbers are, and
// `src/engine`'s generated tables hold the answers, so the interface can show
// hertz, seconds, decibels and Q instead. Where a parameter has no measured table,
// the reference's own display string is used, which for the effects and the
// tunings already carries a unit.
//
// Regenerate after any change to those tables. The generated file is checked in so
// the interface can be opened without a build step.
package main

import "core:fmt"
import "core:os"
import "core:strings"

import patch "../../src/patch"
import registry "../../src/registry"

OUT_PATH :: "ui/params.js"

js_escape :: proc(s: string, b: ^strings.Builder) {
	for c in transmute([]u8)s {
		switch c {
		case '"':
			strings.write_string(b, "\\\"")
		case '\\':
			strings.write_string(b, "\\\\")
		case '\n', '\r', '\t':
			strings.write_string(b, " ")
		case:
			strings.write_byte(b, c)
		}
	}
}

main :: proc() {
	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	strings.write_string(&b, `// Code generated by "odin run tools/uiparams"; do not edit.
//
// The reference Synth1's parameter table, with each position's value in a real
// unit wherever this project has measured one. Method and provenance are in
// docs/null-test.md; the tables this is built from are the generated files in
// src/engine.
//
// Per parameter:
//   i     parameter index, as the engine and the .sy1 format number them
//   name  the reference's own short name
//   def   the stored integer that reproduces the plugin's default
//   n     how many positions the control has
//   unit  suffix for the value readout, "" when the value text carries its own
//   v     the value at each position, in order
//   s     the stored integer each position writes, omitted when it is the position
//
// `)
	fmt.sbprintf(&b, "%v parameters.\nwindow.SYNTH1_PARAMS = [\n", patch.PARAMETER_COUNT)

	for index in 0 ..< patch.PARAMETER_COUNT {
		p := patch.PARAMETERS[index]
		states := patch.parameter_states(index)


		strings.write_byte(&b, '{')
		fmt.sbprintf(&b, "i:%v,name:\"", index)
		js_escape(p.name, &b)
		fmt.sbprintf(&b, "\",def:%v,n:%v", p.default, len(states))

		suffix := registry.value_unit_suffix(index)
		if suffix != "" {
			fmt.sbprintf(&b, ",unit:\"%v\"", suffix)
		}

		if p.continuous || len(states) == 0 {
			// 86..89 read back as a fraction and have no state table at all.
			fmt.sbprintf(&b, ",n:%v,cont:1", patch.CONTINUOUS_DENOMINATOR)
			strings.write_string(&b, "},\n")
			continue
		}

		strings.write_string(&b, ",v:[")
		for position in 0 ..< len(states) {
			if position > 0 {
				strings.write_byte(&b, ',')
			}
			strings.write_byte(&b, '"')
			js_escape(registry.value_text(index, position), &b)
			strings.write_byte(&b, '"')
		}
		strings.write_byte(&b, ']')

		// The stored integer per position, when it is not simply the position.
		//
		// It differs for every display-keyed parameter whose displays are not in
		// order, which is where this project has twice been caught: the LFO
		// waveforms of 42 and 47 list their six states as 0, 1, 5, 2, 3, 4.
		needs_steps := false
		for position in 0 ..< len(states) {
			if stored_for_position(index, position) != position {
				needs_steps = true
				break
			}
		}
		if needs_steps {
			strings.write_string(&b, ",s:[")
			for position in 0 ..< len(states) {
				if position > 0 {
					strings.write_byte(&b, ',')
				}
				fmt.sbprintf(&b, "%v", stored_for_position(index, position))
			}
			strings.write_byte(&b, ']')
		}
		strings.write_string(&b, "},\n")
	}
	strings.write_string(&b, "];\n")

	// The error itself, not just that there was one. This runs in CI, where the
	// difference between "no such directory" and "permission denied" is the
	// difference between reading the log and guessing.
	if err := os.write_entire_file(OUT_PATH, transmute([]u8)strings.to_string(b)); err != nil {
		fmt.eprintfln("uiparams: could not write %v: %v", OUT_PATH, err)
		os.exit(1)
	}
	fmt.printfln("wrote %v (%v parameters)", OUT_PATH, patch.PARAMETER_COUNT)
}

// The stored integer that selects a given position.
//
// For a display-keyed parameter the plugin selects the state whose display equals
// the stored integer, so the interface has to write that display rather than the
// index. `resolved_position` is the inverse and this has to agree with it.
stored_for_position :: proc(index, position: int) -> int {
	states := patch.parameter_states(index)
	if position < 0 || position >= len(states) {
		return position
	}
	if !patch.PARAMETERS[index].display_keyed {
		return position
	}
	if d, ok := patch.display_integer(states[position].display); ok {
		return d
	}
	return position
}
