// uibank - turn a directory of .sy1 patches into the bank the interface reads.
//
//   odin run tools/uibank -- patches/incoming/soundbank00 "Bank 00"
//
// Emitted as JavaScript assigning a global, exactly like `ui/params.js`, and for
// the same reason: the interface has no bundler, no module loader and no
// dependencies, and a page opened straight off the filesystem cannot fetch a data
// file at all. A generated `.js` needs no parser and no network.
//
// It is not YAML for the same reason. YAML would mean shipping a parser of about
// a hundred kilobytes into a project that has none, to read a file no human is
// ever going to edit -- every one of these comes out of `src/patch`'s own reader,
// which is the measured one.
//
// A word about what goes in here. The factory banks under `patches/incoming` are
// Synth1's, not this project's, so the generated file is not committed and the
// published page does not carry it. Point this at patches of your own before
// putting a bank on a public page.
package main

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"

import patch "../../src/patch"

main :: proc() {
	args := os.args[1:]
	dir := len(args) >= 1 ? args[0] : "patches/incoming/soundbank00"
	label := len(args) >= 2 ? args[1] : "Bank"
	out_path := len(args) >= 3 ? args[2] : "ui/bank.js"

	entries, dir_err := os.read_directory_by_path(dir, -1, context.allocator)
	if dir_err != nil {
		fmt.eprintfln("uibank: cannot read %q: %v", dir, dir_err)
		os.exit(1)
	}
	defer os.file_info_slice_delete(entries, context.allocator)

	// Sorted, so the bank is in the order the files are numbered rather than in
	// whatever order the filesystem happens to return.
	slice.sort_by(entries, proc(a, b: os.File_Info) -> bool {
		return a.name < b.name
	})

	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	fmt.sbprintf(&b, `// Code generated by "odin run tools/uibank"; do not edit.
//
// A bank of patches for the interface, read out of .sy1 files by src/patch's own
// parser. Each entry is a name and the 99 stored integers a patch is.
//
// Not committed: see tools/uibank/main.odin on whose patches these are.
window.SYNTH1_BANK = {{ label: "%v", patches: [
`, label)

	loaded := 0
	skipped := 0
	for entry in entries {
		if !strings.has_suffix(strings.to_lower(entry.name), ".sy1") {
			continue
		}
		data, read_err := os.read_entire_file(entry.fullpath, context.allocator)
		if read_err != nil {
			skipped += 1
			continue
		}
		defer delete(data)

		parsed, perr := patch.parse_sy1(data)
		if perr != .None {
			skipped += 1
			continue
		}

		name := parsed.name
		if name == "" {
			name = entry.name
		}

		strings.write_byte(&b, '{')
		strings.write_string(&b, "n:\"")
		for c in transmute([]u8)name {
			switch c {
			case '"':
				strings.write_string(&b, "\\\"")
			case '\\':
				strings.write_string(&b, "\\\\")
			case '\n', '\r', '\t':
				strings.write_byte(&b, ' ')
			case:
				if c >= 0x20 && c < 0x7F {
					strings.write_byte(&b, c)
				}
			}
		}
		strings.write_string(&b, "\",v:[")
		for i in 0 ..< patch.PARAMETER_COUNT {
			if i > 0 {
				strings.write_byte(&b, ',')
			}
			fmt.sbprintf(&b, "%v", parsed.values[i])
		}
		strings.write_string(&b, "]},\n")
		loaded += 1
	}

	strings.write_string(&b, "] };\n")

	if os.write_entire_file(out_path, transmute([]u8)strings.to_string(b)) != nil {
		fmt.eprintfln("uibank: could not write %v", out_path)
		os.exit(1)
	}
	fmt.printfln("wrote %v: %v patches from %v (%v skipped)", out_path, loaded, dir, skipped)
}
