// uibank - turn a bank of patches into the one the interface reads.
//
//   odin run tools/uibank                                    # the factory bank
//   odin run tools/uibank -- <dir of .sy1> "Their Bank"       # somebody else's
//
// Emitted as JavaScript assigning a global, exactly like `ui/params.js`, and for
// the same reason: the interface has no bundler, no module loader and no
// dependencies, and a page opened straight off the filesystem cannot fetch a data
// file at all. A generated `.js` needs no parser and no network.
//
// It is not YAML for the same reason. YAML would mean shipping a parser of about
// a hundred kilobytes into a project that has none, to read a file no human is
// ever going to edit -- every one of these comes out of `src/patch`'s own reader,
// which is the measured one.
//
// A word about what goes in here. The default source is patches/quesynth, which
// is this project's own bank, so the result is committed and the published page
// carries it. The banks under patches/incoming are Synth1's: pointing this at
// them produces a file that must not be committed or published.
package main

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"

import patch "../../src/patch"

// One entry of the bank the interface reads: a name and the ninety-nine stored
// integers. Collected from either source before anything is written, so the
// emitter below does not care which one it came from.
Entry :: struct {
	name:   string,
	values: [patch.PARAMETER_COUNT]int,
}

main :: proc() {
	args := os.args[1:]
	source := len(args) >= 1 ? args[0] : "patches/quesynth/factory.json"
	label := len(args) >= 2 ? args[1] : "Factory"
	out_path := len(args) >= 3 ? args[2] : "ui/bank.js"

	entries_out: [dynamic]Entry
	defer delete(entries_out)
	skipped := 0

	// A JSON bank, or a directory of .sy1 files.
	//
	// The JSON one is this project's own format and is what the factory bank is
	// written in; the directory reader stays because pointing this at somebody's
	// existing Synth1 patches is the other reason it exists.
	if strings.has_suffix(strings.to_lower(source), ".json") {
		data, read_err := os.read_entire_file(source, context.allocator)
		if read_err != nil {
			fmt.eprintfln("uibank: cannot read %q: %v", source, read_err)
			os.exit(1)
		}
		defer delete(data, context.allocator)

		bank, bank_err := patch.parse_bank_json(data)
		if bank_err != .None {
			fmt.eprintfln("uibank: cannot read %q: %v", source, bank_err)
			os.exit(1)
		}
		defer patch.destroy_bank(bank)

		if len(args) < 2 && bank.name != "" {
			label = strings.clone(bank.name)
		}
		for p in bank.patches {
			entry := Entry{name = p.name}
			entry.values = p.values
			append(&entries_out, entry)
		}
		emit(entries_out[:], label, out_path, source, skipped)
		return
	}

	dir := source
	entries, dir_err := os.read_directory_by_path(dir, -1, context.allocator)
	if dir_err != nil {
		fmt.eprintfln("uibank: cannot read %q: %v", dir, dir_err)
		os.exit(1)
	}
	defer os.file_info_slice_delete(entries, context.allocator)

	// Sorted, so the bank is in the order the files are numbered rather than in
	// whatever order the filesystem happens to return.
	slice.sort_by(entries, proc(a, b: os.File_Info) -> bool {
		return a.name < b.name
	})

	for entry in entries {
		if !strings.has_suffix(strings.to_lower(entry.name), ".sy1") {
			continue
		}
		data, read_err := os.read_entire_file(entry.fullpath, context.allocator)
		if read_err != nil {
			skipped += 1
			continue
		}
		defer delete(data, context.allocator)

		parsed, perr := patch.parse_sy1(data)
		if perr != .None {
			skipped += 1
			continue
		}

		name := parsed.name
		if name == "" {
			name = entry.name
		}
		// Cloned: parse_sy1 borrows the name out of `data`, which is freed at
		// the end of this iteration.
		collected := Entry{name = strings.clone(name)}
		collected.values = parsed.values
		append(&entries_out, collected)
	}

	emit(entries_out[:], label, out_path, dir, skipped)
}

// Write the bank as the JavaScript the interface loads.
//
// Shared by both readers so the emitted file cannot depend on where the patches
// came from -- the panel has no idea whether a bank started as JSON or as a
// directory of .sy1, and nothing here should let it find out.
emit :: proc(entries: []Entry, label, out_path, source: string, skipped: int) {
	b := strings.builder_make()
	defer strings.builder_destroy(&b)

	fmt.sbprintf(&b, `// Code generated by "odin run tools/uibank"; do not edit.
//
// A bank of patches for the interface. Each entry is a name and the 99 stored
// integers a patch is.
//
// Regenerate with "odin run tools/uibank". See that file on whose patches
// these are before publishing a bank built from anything else.
window.SYNTH1_BANK = {{ label: "%v", patches: [
`, label)

	for entry in entries {
		strings.write_byte(&b, '{')
		strings.write_string(&b, "n:\"")
		for c in transmute([]u8)entry.name {
			switch c {
			case '"':
				strings.write_string(&b, "\\\"")
			case '\\':
				strings.write_string(&b, "\\\\")
			case '\n', '\r', '\t':
				strings.write_byte(&b, ' ')
			case:
				if c >= 0x20 && c < 0x7F {
					strings.write_byte(&b, c)
				}
			}
		}
		strings.write_string(&b, "\",v:[")
		for i in 0 ..< patch.PARAMETER_COUNT {
			if i > 0 {
				strings.write_byte(&b, ',')
			}
			fmt.sbprintf(&b, "%v", entry.values[i])
		}
		strings.write_string(&b, "]},\n")
	}

	strings.write_string(&b, "] };\n")

	if os.write_entire_file(out_path, transmute([]u8)strings.to_string(b)) != nil {
		fmt.eprintfln("uibank: could not write %v", out_path)
		os.exit(1)
	}
	fmt.printfln("wrote %v: %v patches from %v (%v skipped)", out_path, len(entries), source, skipped)
}
