// Write the terminal UI's parameter layout from the browser panel's.
//
// ui/layout.js decides which section and which group every control sits in, and
// in what order. The TUI shows the same sections and groups, so it reads them
// from here rather than keeping a second opinion -- but it is an Odin program
// that must not need Node to run, so the layout is carried over as a generated
// table, the way tools/uiparams carries the measured tables the other way.
// Run after changing ui/layout.js; tests/ui/tui-layout.test.mjs fails until
// the table is regenerated.
//
//   node tools/tuilayout.mjs

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import {fileURLToPath} from "node:url";

const REPOSITORY = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const LAYOUT_SOURCE = path.join(REPOSITORY, "ui", "layout.js");
export const LAYOUT_TABLE = path.join(REPOSITORY, "hosts", "standalone", "tui", "layout.odin");

// The sections as the panel builds them: each with its groups, each group the
// parameter indices of its controls in panel order.
export function readLayout() {
  const context = vm.createContext({window: {}});
  vm.runInContext(fs.readFileSync(LAYOUT_SOURCE, "utf8"), context, {filename: LAYOUT_SOURCE});
  return Array.from(context.window.SYNTH1_LAYOUT, panel => ({
    title: panel.title,
    groups: Array.from(panel.groups || [{label: "", controls: panel.controls || []}], group => ({
      label: group.label || "",
      params: Array.from(group.controls, control => control.p),
    })),
  }));
}

export function generate(layout = readLayout()) {
  const out = [
    "package tui",
    "",
    "// Generated by tools/tuilayout.mjs from ui/layout.js. Do not edit: change the",
    "// browser panel's layout and run `node tools/tuilayout.mjs`.",
    "",
    "Layout_Group :: struct {",
    "\tlabel:  string,",
    "\tparams: []int,",
    "}",
    "",
    "Layout_Section :: struct {",
    "\ttitle:  string,",
    "\tgroups: []Layout_Group,",
    "}",
    "",
    "PANEL_LAYOUT := []Layout_Section {",
  ];
  for (const section of layout) {
    out.push(`\t{${JSON.stringify(section.title)}, {`);
    for (const group of section.groups) {
      out.push(`\t\t{${JSON.stringify(group.label)}, {${group.params.join(", ")}}},`);
    }
    out.push("\t}},");
  }
  out.push("}", "");
  return out.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(LAYOUT_TABLE, generate());
  console.log(`wrote ${path.relative(REPOSITORY, LAYOUT_TABLE)}`);
}
